name: "dau Maharaj"

on:
  workflow_dispatch:

jobs:
  terraform-job:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
         version: 1.13.0
          
