name: "dau Maharaj"

on:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read

jobs:
  terraform-job:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.3.0   # 1.13.0 nahi hai, latest 1.3.x/1.4.x use karo

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: 71d633da-0f9c-4679-ab81-dcbe6b1c930a
          tenant-id: b045856a-3dc6-4e42-9811-6dd226cc9800
          subscription-id: 59bea627-7b7a-4e47-bec4-fb0b51214f26
          

          
                
          
