name: "dau Maharaj"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-job:
    runs-on: self-hosted
    timeout-minutes: 60   # optional safeguard
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.3.0   # correct version

      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: 71d633da-0f9c-4679-ab81-dcbe6b1c930a
          tenant-id: b045856a-3dc6-4e42-9811-6dd226cc9800
          subscription-id: 59bea627-7b7a-4e47-bec4-fb0b51214f26

  
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environments/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=tfplan
        working-directory: environments/dev

        
  manual-approval:
    runs-on: ubuntu-latest
    needs: terraform-job
    steps:
    - name: Await Manual Approval
      uses: trstringer/manual-approval@v1

      secret: ${{ github.TOKEN }}
      approvers: kuldeep805
        timeout-minutes: 60
      
      
      

    


          

          
                
          
